---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nettools
  labels:
    app: nettools
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nettools
  template:
    metadata:
      labels:
        app: nettools
      annotations:
        networkservicemesh.io: kernel://vl3-dataplane-interrupt/nsm-1
    spec:
      containers:
      - name: nettools
        image: aeciopires/nettools:1.0.0
        imagePullPolicy: IfNotPresent
        # simple `sleep` command would work
        # but we need `trap` to be able to delete pods quckly
        command: ["/bin/sh", "-c", "trap : TERM INT; sleep infinity & wait"]
