---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-policy-based-routing

resources:
- ns-policy-based-routing.yaml
- client.yaml
- netsvc.yaml
- ../../../apps/nse-kernel-pbr

patches:
- path: patch-nse.yaml
