---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-memif2ethernet2kernel

resources:
- ns-memif2ethernet2kernel.yaml
- netsvc.yaml
- ../../../apps/nsc-memif
- nse-kernel.yaml

patches:
- path: patch-nsc.yaml
- path: patch-nse.yaml
